In [6]:
'''
Web Scraping - Beautiful Soup
'''

# importing required libraries
import urllib.request 
from bs4 import BeautifulSoup

# URL TO SCRAP
wiki = "https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India"
#Query the website and return the html to the variable 'page'
#For python 3 use urllib.request.urlopen(wiki)
page = urllib.request.urlopen(wiki) 

#Parse the html in the 'page' variable, and store it in Beautiful Soup format
soup = BeautifulSoup(page,features='html.parser')
print('\n\nPage Scrapped !!!\n\n')


print('\n\nTITLE OF THE PAGE\n\n')
print(soup.title.string)

print('\n\nALL THE URLs IN THE WEB PAGE\n\n')

all_links = soup.find_all('a')

print('Total number of URLs present = ',len(all_links)) 

print('\n\nLast 5 URLs in the page are : \n')

if len(all_links) > 5 :
  
  last_5 = all_links[len(all_links)-5:]
  for url in last_5 :
    print(url.get('href'))
right_table=soup.find('table', class_='wikitable sortable plainrowheaders')
right_table
#Generate lists
A=[]
B=[]
C=[]
D=[]
E=[]
F=[]
G=[]
for row in right_table.findAll("tr"):
    cells = row.findAll('td')
    states=row.findAll('th') #To store second column data
    if len(cells)==6: #Only extract table body not heading
        A.append(cells[0].find(text=True))
        B.append(states[0].find(text=True))
        C.append(cells[1].find(text=True))
        D.append(cells[2].find(text=True))
        E.append(cells[3].find(text=True))
        F.append(cells[4].find(text=True))
        G.append(cells[5].find(text=True))
#import pandas to convert list to data frame
import pandas as pd
df=pd.DataFrame(A,columns=['Number'])
df['State/UT']=B
df['Admin_Capital']=C
df['Legislative_Capital']=D
df['Judiciary_Capital']=E
df['Year_Capital']=F
df['Former_Capital']=G
print(df)
df.to_csv('joker.csv')

Page Scrapped !!!




TITLE OF THE PAGE


List of state and union territory capitals in India - Wikipedia


ALL THE URLs IN THE WEB PAGE


Total number of URLs present =  433


Last 5 URLs in the page are :

https://www.mediawiki.org/wiki/Special:MyLanguage/How_to_contribute
https://foundation.wikimedia.org/wiki/Cookie_statement
//en.m.wikipedia.org/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&mobileaction=toggle_view_mobile
https://wikimediafoundation.org/
https://www.mediawiki.org/
   Number                             State/UT       Admin_Capital  \
0      1
          Andaman and Nicobar Islands          Port Blair
1      2
                       Andhra Pradesh           Hyderabad
2      3
                    Arunachal Pradesh            Itanagar
3      4
                                Assam              Dispur
4      5
                                Bihar               Patna
5      6
                           Chandigarh          Chandigarh
6      7
                         Chhattisgarh              Raipur
7      8
               Dadra and Nagar Haveli            Silvassa
8      9
                        Daman and Diu               Daman
9     10
  National Capital Territory of Delhi           New Delhi
10    11
                                  Goa              Panaji
11    12
                              Gujarat         Gandhinagar
12    13
                              Haryana          Chandigarh
13    14
                     Himachal Pradesh              Shimla
14    15
                    Jammu and Kashmir            Srinagar
15    16
                            Jharkhand              Ranchi
16    17
                            Karnataka           Bangalore
17    18
                               Kerala  Thiruvananthapuram
18    19
                               Ladakh                 Leh
19    20
                          Lakshadweep           Kavaratti
20    21
                       Madhya Pradesh              Bhopal
21    22
                          Maharashtra              Mumbai
22    23
                              Manipur              Imphal
23    24
                            Meghalaya            Shillong
24    25
                              Mizoram              Aizawl
25    26
                             Nagaland              Kohima
26    27
                               Odisha         Bhubaneswar
27    28
                           Puducherry         Pondicherry
28    29
                               Punjab          Chandigarh
29    30
                            Rajasthan              Jaipur
30    31
                               Sikkim             Gangtok
31    32
                           Tamil Nadu             Chennai
32    33
                            Telangana           Hyderabad
33    34
                              Tripura            Agartala
34    35
                        Uttar Pradesh             Lucknow
35    36
                          Uttarakhand            Dehradun
36    37
                          West Bengal             Kolkata

    Legislative_Capital  Judiciary_Capital Year_Capital         Former_Capital
0                    —
           Kolkata
        1955
  Calcutta (1945–1955)

1             Amaravati          Amaravati         1956                Kurnool
2             Itanagar
           Guwahati        1986
                     —

3              Guwahati          Guwahati
        1975
               Shillong
4                Patna
             Patna
        1912
                     —

5                    —
        Chandigarh
        1966
                     —

6               Raipur
           Bilaspur        2000
                     —

7                    —
             Mumbai        1945
    Mumbai (1954–1961)
8                    —
             Mumbai        1987
              Ahmedabad
9            New Delhi
         New Delhi
        1931
                     —

10             Porvorim             Mumbai        1961
    Panaji (1961–1987)

11         Gandhinagar
          Ahmedabad        1960
              Ahmedabad
12          Chandigarh
        Chandigarh
        1966
                     —

13      Shimla (Summer)           Shimla
         1971               Bilaspur
14    Srinagar (Summer)  Srinagar (Summer)        2019
                     —

15              Ranchi
            Ranchi
        2000
                     —

16           Bangalore
         Bangalore
        1940
              (Mysore)

17  Thiruvananthapuram
              Kochi        1956
                     —

18                   —
  Srinagar (Summer)        2019
      Srinagar (Summer)
19                   —
              Kochi        1956
                     —

20              Bhopal
           Jabalpur        1956
                 Nagpur
21     Mumbai (Summer)
            Mumbai
        1818
                     —

22              Imphal
            Imphal
        1947
                     —

23            Shillong
          Shillong
        1970
                     —

24              Aizawl
           Guwahati        1972
                     —

25              Kohima
           Guwahati        1963
                     —

26         Bhubaneswar
            Cuttack        1948
                Cuttack
27         Pondicherry
            Chennai        1954
                 Madras
28          Chandigarh
        Chandigarh
        1966
                     —

29              Jaipur
            Jodhpur        1950
                     —

30             Gangtok
           Gangtok
        1890
                     —

31             Chennai
           Chennai
        1956
                     —

32           Hyderabad
         Hyderabad
        2014
                     —

33            Agartala
          Agartala
        1956
                     —

34             Lucknow
          Allahabad        1938
                     —

35            Dehradun
           Nainital        2000
                     —

36             Kolkata
           Kolkata
        1947
                     —

In [7]:
import requests
page = requests.get("https://weather.com/en-IN/weather/tenday/l/INKA0344:1:IN")
from bs4 import BeautifulSoup
soup=BeautifulSoup(page.content,"html.parser")
all=soup.find("div",{"class":"locations-title ten-day-page-title"}).find("h1").text
table=soup.find_all("table",{"class":"twc-table"})
l=[]
for items in table:
 for i in range(len(items.find_all("tr"))-1):
  d = {}  
  d["day"]=items.find_all("span",{"class":"date-time"})[i].text
  d["date"]=items.find_all("span",{"class":"day-detail"})[i].text
  d["desc"]=items.find_all("td",{"class":"description"})[i].text 
  d["temp"]=items.find_all("td",{"class":"temp"})[i].text 
  d["precip"]=items.find_all("td",{"class":"precip"})[i].text
  d["wind"]=items.find_all("td",{"class":"wind"})[i].text  
  d["humidity"]=items.find_all("td",{"class":"humidity"})[i].text 
  l.append(d)
import pandas
df = pandas.DataFrame(l)
df.to_csv("output.csv")

In [1]:
from selenium import webdriver 
import time 


from bs4 import BeautifulSoup

url = 'https://www.webscraper.io/test-sites/e-commerce/ajax/computers/laptops'

# Change argument to the location you installed the chrome driver
# (see selenium installation instructions, or get the driver for your
# system from https://sites.google.com/a/chromium.org/chromedriver/downloads)
# set webdriver path here it may vary 
driver = webdriver.Chrome(executable_path ="C:\Program Files (x86)\Google\Chrome\chromedriver.exe")
driver.get(url)

# Give the javascript time to render
time.sleep(1)

# Now we have the page, let BeautifulSoup do the rest!
soup = BeautifulSoup(driver.page_source)

# The text containing title and price are in a
# div with class caption.
for caption in soup.find_all(class_='caption'):
    product_name = caption.find(class_='title').text
    price = caption.find(class_='pull-right price').text
    print(product_name, price)

Asus VivoBook X4 $295.99
Prestigio SmartB $299.00
Prestigio SmartB $299.00
Aspire E1-510 $306.99
Lenovo V110-15IA $321.94
Lenovo V110-15IA $356.49

In [37]:
from selenium import webdriver  # Need To import webdriver from selenium package
from bs4 import BeautifulSoup as bs
import time

driver = webdriver.Chrome(executable_path ="C:\Program Files (x86)\Google\Chrome\chromedriver.exe")

driver.get("http://m.imdb.com/feature/bornondate")

time.sleep(1)

html = driver.page_source
driver.close()

soup = bs(html, 'html5lib')
# print soup.prettify()
##for tags in soup.currentTag():
## print tags

##celeb_records = soup.find_all('a')
##for info in celeb_records:
## print info

## step 1 : Iterating through names of celebrities


celeb_name = []
name = soup.find_all('h3', class_='lister-item-header')

for info in name:
    # print info.text
    celeb_name.append(info.text)

## step 2 : Iterating through details of celebrities
# below are the list of celebrities detail

celeb_detail = []
detail = soup.find_all('p')
for details in detail:
    #print(details.text)
    celeb_detail.append(details.text)
celeb_images = []
images = soup.find_all('div', class_='lister-item-imag')
for image in images:
    # print image.img["src"]
    celeb_images.append(image.img["src"])
import pandas
a=[celeb_name]
b=[celeb_detail]
df= pandas.DataFrame(a)
bf=pandas.DataFrame(b)
print(df)
print(bf)
df.to_csv("imdb.csv")
bf.to_csv("imdb details.csv")

                                                  0   \
0  \n                 1. \n Leonardo DiCaprio\n  ...

                                                  1   \
0  \n                 2. \n Demi Moore\n         ...

                                                  2   \
0  \n                 3. \n Bill Moseley\n       ...

                                                  3   \
0  \n                 4. \n Stanley Tucci\n      ...

                                                  4   \
0  \n                 5. \n Tye Sheridan\n       ...

                                                  5   \
0  \n                 6. \n Calista Flockhart\n  ...

                                                  6   \
0  \n                 7. \n Ashleigh Cummings\n  ...

                                                  7   \
0  \n                 8. \n Alison Doody\n       ...

                                                  8   \
0  \n                 9. \n Adam Beach\n         ...

                                                  9   \
0  \n                 10. \n Scoot McNairy\n     ...

                         ...                          \
0                        ...

                                                  40  \
0  \n                 41. \n Dean Jagger\n       ...

                                                  41  \
0  \n                 42. \n Gerard Horan\n      ...

                                                  42  \
0  \n                 43. \n Alan Vint\n         ...

                                                  43  \
0  \n                 44. \n Camille Hyde\n      ...

                                                  44  \
0  \n                 45. \n Susan Kohner\n      ...

                                                  45  \
0  \n                 46. \n Arianna Ortiz\n     ...

                                                  46  \
0  \n                 47. \n Pat O'Brien\n       ...

                                                  47  \
0  \n                 48. \n Stephen Lee\n       ...

                                                  48  \
0  \n                 49. \n Katie Chonacas\n    ...

                                                  49
0  \n                 50. \n Michael Arndt\n     ...

[1 rows x 50 columns]
                                                 0    \
0  \n                Movies,\n                TV\...

                                                 1    \
0  \n                                \n          ...

                                                 2    \
0  \n                Celebs,\n                Eve...

                                                 3    \
0  \n                                \n          ...

                                                 4                  5    \
0  \n                News &\n                Comm...  \n    Watchlist\n

         6                                               7    \
0  \n \n      Find industry contacts & talent representation

                                                 8    \
0  Access in-development titles not available on ...

                                                9    \
0  Get the latest news from leading industry trades

                         ...                          \
0                        ...

                                                 103  \
0  \n    Arianna Ortiz was born on November 11, 1...

                                                 104  \
0  \n                         Actor |\n Some Like...

                                                 105  \
0  \n    Although he came to be called "Hollywood...

                                                 106  \
0  \n                         Actor |\n The Negot...

                                                 107  \
0  \n    Stephen Lee was born in Englewood New Je...

                                                 108  \
0  \n                         Actress |\n A Perfe...

                                                 109  \
0  \n    There are few women in the entertainment...

                                                 110  \
0  \n                         Writer |\n Star War...

                                                 111  \
0  \n    Michael Arndt was born on November 11, 1...

                                                 112
0  Find showtimes, watch trailers, browse photos,...

[1 rows x 113 columns]

In [2]:
import requests 
from bs4 import BeautifulSoup 
import csv 
import pandas as pd
names=[]
prices=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
CryptoCurrenciesUrl = "https://in.finance.yahoo.com/currencies"
r= requests.get(CryptoCurrenciesUrl)
data=r.text
soup=BeautifulSoup(data)
 
counter = 40
for i in range(40, 404, 14):
   for listing in soup.find_all('tr', attrs={'data-reactid':i}):
      for name in listing.find_all('td', attrs={'data-reactid':i+3}):
         names.append(name.text)
      for price in listing.find_all('td', attrs={'data-reactid':i+4}):
         prices.append(price.text)
      for change in listing.find_all('td', attrs={'data-reactid':i+5}):
         changes.append(change.text)
      for percentChange in listing.find_all('td', attrs={'data-reactid':i+7}):
         percentChanges.append(percentChange.text)
pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges})

      Names       Prices    Change  % Change
0   USD/INR      71.4400   +0.0900  +0.1261%
1   EUR/INR      78.7912   +0.1436    +0.18%
2   GBP/INR      91.4696   +0.2981    +0.33%
3   AED/INR      19.4170   +0.0340    +0.18%
4   INR/JPY       1.5228   -0.0052    -0.34%
5   SGD/INR      52.4750   -0.0280    -0.05%
6   USD/IDR  14,065.0000  +55.0000  +0.3926%
7   USD/THB      30.2900   -0.1000  -0.3291%
8   USD/MYR       4.1435   +0.0125  +0.3026%
9   USD/ZAR      14.8685   +0.0073  +0.0491%
10  USD/RUB      63.8914   +0.1020  +0.1599%
11  AUD/USD       0.6866   -0.0003  -0.0481%
12  AUD/JPY      74.7970   -0.2230    -0.30%
13  NZD/USD       0.6372   +0.0040  +0.6244%
14  EUR/USD       1.1034   +0.0009  +0.0772%
15  EUR/CAD       1.4582   +0.0009    +0.07%
16  USD/JPY     108.9630   -0.2670  -0.2444%
17  GBP/USD       1.2805   +0.0031  +0.2459%
18  USD/CHF       0.9952   -0.0020  -0.2016%
19  USD/CAD       1.3219   -0.0004  -0.0272%
20  EUR/JPY     120.1910   -0.1990    -0.17%
21  GBP/JPY     139.5170   -0.0830    -0.06%
22  EUR/GBP       0.8615   -0.0008    -0.10%
23  EUR/SEK      10.7126   +0.0201    +0.19%
24  EUR/CHF       1.0978   -0.0009    -0.09%
25  EUR/HUF     334.2300   +0.8400    +0.25%

In [7]:
import requests 
from bs4 import BeautifulSoup 
import csv 
import pandas as pd
prices=[]
names=[]
changes=[]
percentChanges=[]
marketCaps=[]
marketTimes=[]
totalVolumes=[]
openInterests=[]
 
CryptoCurrenciesUrl = "https://in.finance.yahoo.com/commodities"
r= requests.get(CryptoCurrenciesUrl)
data=r.text
soup=BeautifulSoup(data)
 
counter = 40
for i in range(40, 404, 14):
   for row in soup.find_all('tbody'):
      for srow in row.find_all('tr'):
         for name in srow.find_all('td', attrs={'class':'data-col1'}):
            names.append(name.text)
         for price in srow.find_all('td', attrs={'class':'data-col2'}):
            prices.append(price.text)
         for time in srow.find_all('td', attrs={'class':'data-col3'}):
            marketTimes.append(time.text)
         for change in srow.find_all('td', attrs={'class':'data-col4'}):
            changes.append(change.text)
         for percentChange in srow.find_all('td', attrs={'class':'data-col5'}):
            percentChanges.append(percentChange.text)
         for volume in srow.find_all('td', attrs={'class':'data-col6'}):
            totalVolumes.append(volume.text)
         for openInterest in srow.find_all('td', attrs={'class':'data-col7'}):
            openInterests.append(openInterest.text)
 
pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges, "Market Time": marketTimes,'Open Interest': openInterests ,"Volume": totalVolumes})

,Names,Prices,Change,% Change,Market Time,Open Interest,Volume
0,Gold Dec 19,"1,466.60",+3.70,+0.25%,5:56AM EST,"445,056","74,274"
1,Silver Dec 19,16.88,+0.06,+0.34%,5:55AM EST,"144,406","21,961"
2,Copper Dec 19,2.6585,-0.0235,-0.88%,5:56AM EST,"120,976","16,634"
3,Crude Oil Dec 19,56.34,-0.90,-1.57%,5:56AM EST,"352,155","101,893"
4,Brent Crude Oil Last Day Financ,61.66,-0.85,-1.36%,5:56AM EST,"33,139","5,545"
5,Natural Gas Dec 19,2.6790,-0.1100,-3.94%,5:56AM EST,"243,443","21,608"
6,Corn Dec 19,374.00,-3.25,-0.86%,5:55AM EST,"621,743","15,559"
7,Oats Dec 19,301.50,+1.75,+0.58%,12:39AM EST,"4,312",21
8,"KC HRW Wheat Futures,Dec-2019,C",418.50,-3.00,-0.71%,5:53AM EST,"140,192","1,688"
9,Rough Rice Nov 19,11.78,-0.02,-0.17%,8:02PM EST,5,25
10,Soybeans Nov 19,926.00,-5.00,-0.54%,5:55AM EST,"1,214","12,367"
11,Feeder Cattle Jan 20,146.275,+0.500,+0.34%,2:04PM EST,"21,397","3,947"
12,Lean Hogs Dec 19,64.10,-0.20,-0.31%,2:04PM EST,"86,134","26,088"
13,Live Cattle Dec 19,119.30,+0.30,+0.25%,2:04PM EST,"131,353","29,563"
14,Cocoa Dec 19,"2,485.00",-18.00,-0.72%,5:44AM EST,"96,280",438
15,Coffee Dec 19,108.15,-1.30,-1.19%,5:46AM EST,"129,606","2,168"
16,Cotton Dec 19,65.81,-0.76,-1.14%,5:46AM EST,"88,467","2,716"
17,Lumber Nov 19,393.90,+0.60,+0.15%,4:04PM EST,192,73
18,Orange Juice Nov 19,100.55,+0.25,+0.25%,1:59PM EST,28,353
19,Sugar #11 Mar 20,12.46,-0.11,-0.88%,5:45AM EST,"503,463","5,374"
20,Gold Dec 19,"1,466.60",+3.70,+0.25%,5:56AM EST,"445,056","74,274"
21,Silver Dec 19,16.88,+0.06,+0.34%,5:55AM EST,"144,406","21,961"
22,Copper Dec 19,2.6585,-0.0235,-0.88%,5:56AM EST,"120,976","16,634"
23,Crude Oil Dec 19,56.34,-0.90,-1.57%,5:56AM EST,"352,155","101,893"
24,Brent Crude Oil Last Day Financ,61.66,-0.85,-1.36%,5:56AM EST,"33,139","5,545"
25,Natural Gas Dec 19,2.6790,-0.1100,-3.94%,5:56AM EST,"243,443","21,608"
26,Corn Dec 19,374.00,-3.25,-0.86%,5:55AM EST,"621,743","15,559"
27,Oats Dec 19,301.50,+1.75,+0.58%,12:39AM EST,"4,312",21
28,"KC HRW Wheat Futures,Dec-2019,C",418.50,-3.00,-0.71%,5:53AM EST,"140,192","1,688"
29,Rough Rice Nov 19,11.78,-0.02,-0.17%,8:02PM EST,5,25
...,...,...,...,...,...,...,...
490,Soybeans Nov 19,926.00,-5.00,-0.54%,5:55AM EST,"1,214","12,367"
491,Feeder Cattle Jan 20,146.275,+0.500,+0.34%,2:04PM EST,"21,397","3,947"
492,Lean Hogs Dec 19,64.10,-0.20,-0.31%,2:04PM EST,"86,134","26,088"
493,Live Cattle Dec 19,119.30,+0.30,+0.25%,2:04PM EST,"131,353","29,563"
494,Cocoa Dec 19,"2,485.00",-18.00,-0.72%,5:44AM EST,"96,280",438
495,Coffee Dec 19,108.15,-1.30,-1.19%,5:46AM EST,"129,606","2,168"
496,Cotton Dec 19,65.81,-0.76,-1.14%,5:46AM EST,"88,467","2,716"
497,Lumber Nov 19,393.90,+0.60,+0.15%,4:04PM EST,192,73
498,Orange Juice Nov 19,100.55,+0.25,+0.25%,1:59PM EST,28,353
499,Sugar #11 Mar 20,12.46,-0.11,-0.88%,5:45AM EST,"503,463","5,374"
500,Gold Dec 19,"1,466.60",+3.70,+0.25%,5:56AM EST,"445,056","74,274"
501,Silver Dec 19,16.88,+0.06,+0.34%,5:55AM EST,"144,406","21,961"
502,Copper Dec 19,2.6585,-0.0235,-0.88%,5:56AM EST,"120,976","16,634"
503,Crude Oil Dec 19,56.34,-0.90,-1.57%,5:56AM EST,"352,155","101,893"
504,Brent Crude Oil Last Day Financ,61.66,-0.85,-1.36%,5:56AM EST,"33,139","5,545"
505,Natural Gas Dec 19,2.6790,-0.1100,-3.94%,5:56AM EST,"243,443","21,608"
506,Corn Dec 19,374.00,-3.25,-0.86%,5:55AM EST,"621,743","15,559"
507,Oats Dec 19,301.50,+1.75,+0.58%,12:39AM EST,"4,312",21
508,"KC HRW Wheat Futures,Dec-2019,C",418.50,-3.00,-0.71%,5:53AM EST,"140,192","1,688"
509,Rough Rice Nov 19,11.78,-0.02,-0.17%,8:02PM EST,5,25
510,Soybeans Nov 19,926.00,-5.00,-0.54%,5:55AM EST,"1,214","12,367"
511,Feeder Cattle Jan 20,146.275,+0.500,+0.34%,2:04PM EST,"21,397","3,947"
512,Lean Hogs Dec 19,64.10,-0.20,-0.31%,2:04PM EST,"86,134","26,088"
513,Live Cattle Dec 19,119.30,+0.30,+0.25%,2:04PM EST,"131,353","29,563"
514,Cocoa Dec 19,"2,485.00",-18.00,-0.72%,5:44AM EST,"96,280",438
515,Coffee Dec 19,108.15,-1.30,-1.19%,5:46AM EST,"129,606","2,168"
516,Cotton Dec 19,65.81,-0.76,-1.14%,5:46AM EST,"88,467","2,716"
517,Lumber Nov 19,393.90,+0.60,+0.15%,4:04PM EST,192,73
518,Orange Juice Nov 19,100.55,+0.25,+0.25%,1:59PM EST,28,353
519,Sugar #11 Mar 20,12.46,-0.11,-0.88%,5:45AM EST,"503,463","5,374"

In [4]:
#https://bit.ly/2NyxdAG
from bs4 import BeautifulSoup
import requests
import re

# Download IMDB's Top 250 data
url = 'http://www.imdb.com/chart/top'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'lxml')

movies = soup.select('td.titleColumn')
links = [a.attrs.get('href') for a in soup.select('td.titleColumn a')]
crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
ratings = [b.attrs.get('data-value') for b in soup.select('td.posterColumn span[name=ir]')]
votes = [b.attrs.get('data-value') for b in soup.select('td.ratingColumn strong')]

imdb = []

# Store each item into dictionary (data), then put those into a list (imdb)
for index in range(0, len(movies)):
    # Seperate movie into: 'place', 'title', 'year'
    movie_string = movies[index].get_text()
    movie = (' '.join(movie_string.split()).replace('.', ''))
    movie_title = movie[len(str(index))+1:-7]
    year = re.search('\((.*?)\)', movie_string).group(1)
    place = movie[:len(str(index))-(len(movie))]
    data = {"movie_title": movie_title,
            "year": year,
            "place": place,
            "star_cast": crew[index],
            "rating": ratings[index],
            "vote": votes[index],
            "link": links[index]}
    imdb.append(data)

for item in imdb:
    print(item['place'], '-', item['movie_title'], '('+item['year']+') -', 'Starring:', item['star_cast'])

1 - The Shawshank Redemption (1994) - Starring: Frank Darabont (dir.), Tim Robbins, Morgan Freeman
2 - The Godfather (1972) - Starring: Francis Ford Coppola (dir.), Marlon Brando, Al Pacino
3 - The Godfather: Part II (1974) - Starring: Francis Ford Coppola (dir.), Al Pacino, Robert De Niro
4 - The Dark Knight (2008) - Starring: Christopher Nolan (dir.), Christian Bale, Heath Ledger
5 - 12 Angry Men (1957) - Starring: Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb
6 - Schindler's List (1993) - Starring: Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes
7 - The Lord of the Rings: The Return of the King (2003) - Starring: Peter Jackson (dir.), Elijah Wood, Viggo Mortensen
8 - Pulp Fiction (1994) - Starring: Quentin Tarantino (dir.), John Travolta, Uma Thurman
9 - Il buono, il brutto, il cattivo (1966) - Starring: Sergio Leone (dir.), Clint Eastwood, Eli Wallach
1 -  Fight Club (1999) - Starring: David Fincher (dir.), Brad Pitt, Edward Norton
11 - The Lord of the Rings: The Fellowship of the Ring (2001) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen
12 - Forrest Gump (1994) - Starring: Robert Zemeckis (dir.), Tom Hanks, Robin Wright
13 - Inception (2010) - Starring: Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt
14 - Star Wars: Episode V - The Empire Strikes Back (1980) - Starring: Irvin Kershner (dir.), Mark Hamill, Harrison Ford
15 - The Lord of the Rings: The Two Towers (2002) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen
16 - Joker (2019) - Starring: Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro
17 - The Matrix (1999) - Starring: Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne
18 - One Flew Over the Cuckoo's Nest (1975) - Starring: Milos Forman (dir.), Jack Nicholson, Louise Fletcher
19 - Goodfellas (1990) - Starring: Martin Scorsese (dir.), Robert De Niro, Ray Liotta
20 - Shichinin no samurai (1954) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura
21 - Se7en (1995) - Starring: David Fincher (dir.), Morgan Freeman, Brad Pitt
22 - Cidade de Deus (2002) - Starring: Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino
23 - La vita è bella (1997) - Starring: Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi
24 - The Silence of the Lambs (1991) - Starring: Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins
25 - It's a Wonderful Life (1946) - Starring: Frank Capra (dir.), James Stewart, Donna Reed
26 - Star Wars (1977) - Starring: George Lucas (dir.), Mark Hamill, Harrison Ford
27 - Saving Private Ryan (1998) - Starring: Steven Spielberg (dir.), Tom Hanks, Matt Damon
28 - Sen to Chihiro no kamikakushi (2001) - Starring: Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette
29 - The Green Mile (1999) - Starring: Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan
30 - Léon (1994) - Starring: Luc Besson (dir.), Jean Reno, Gary Oldman
31 - Interstellar (2014) - Starring: Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway
32 - The Usual Suspects (1995) - Starring: Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne
33 - Seppuku (1962) - Starring: Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama
34 - The Lion King (1994) - Starring: Roger Allers (dir.), Matthew Broderick, Jeremy Irons
35 - American History X (1998) - Starring: Tony Kaye (dir.), Edward Norton, Edward Furlong
36 - Back to the Future (1985) - Starring: Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd
37 - The Pianist (2002) - Starring: Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann
38 - Terminator 2: Judgment Day (1991) - Starring: James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton
39 - Modern Times (1936) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard
40 - Psycho (1960) - Starring: Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh
41 - The Intouchables (2011) - Starring: Olivier Nakache (dir.), François Cluzet, Omar Sy
42 - Gladiator (2000) - Starring: Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix
43 - City Lights (1931) - Starring: Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill
44 - The Departed (2006) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon
45 - Whiplash (2014) - Starring: Damien Chazelle (dir.), Miles Teller, J.K. Simmons
46 - Once Upon a Time in the West (1968) - Starring: Sergio Leone (dir.), Henry Fonda, Charles Bronson
47 - Gisaengchung (2019) - Starring: Joon-ho Bong (dir.), Kang-ho Song, Sun-kyun Lee
48 - The Prestige (2006) - Starring: Christopher Nolan (dir.), Christian Bale, Hugh Jackman
49 - Casablanca (1942) - Starring: Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman
50 - Hotaru no haka (1988) - Starring: Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi
51 - Rear Window (1954) - Starring: Alfred Hitchcock (dir.), James Stewart, Grace Kelly
52 - Avengers: Endgame (2019) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Evans
53 - Nuovo Cinema Paradiso (1988) - Starring: Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale
54 - Alien (1979) - Starring: Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt
55 - Raiders of the Lost Ark (1981) - Starring: Steven Spielberg (dir.), Harrison Ford, Karen Allen
56 - Memento (2000) - Starring: Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss
57 - Apocalypse Now (1979) - Starring: Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando
58 - The Great Dictator (1940) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard
59 - The Lives of Others (2006) - Starring: Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck
60 - Django Unchained (2012) - Starring: Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz
61 - Avengers: Infinity War (2018) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth
62 - The Shining (1980) - Starring: Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall
63 - Paths of Glory (1957) - Starring: Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker
64 - Spider-Man: Into the Spider-Verse (2018) - Starring: Bob Persichetti (dir.), Shameik Moore, Jake Johnson
65 - WALL·E (2008) - Starring: Andrew Stanton (dir.), Ben Burtt, Elissa Knight
66 - Mononoke-hime (1997) - Starring: Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida
67 - Sunset Blvd (1950) - Starring: Billy Wilder (dir.), William Holden, Gloria Swanson
68 - Dr Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) - Starring: Stanley Kubrick (dir.), Peter Sellers, George C. Scott
69 - Oldeuboi (2003) - Starring: Chan-wook Park (dir.), Min-sik Choi, Ji-Tae Yoo
70 - Witness for the Prosecution (1957) - Starring: Billy Wilder (dir.), Tyrone Power, Marlene Dietrich
71 - The Dark Knight Rises (2012) - Starring: Christopher Nolan (dir.), Christian Bale, Tom Hardy
72 - Once Upon a Time in America (1984) - Starring: Sergio Leone (dir.), Robert De Niro, James Woods
73 - Aliens (1986) - Starring: James Cameron (dir.), Sigourney Weaver, Michael Biehn
74 - American Beauty (1999) - Starring: Sam Mendes (dir.), Kevin Spacey, Annette Bening
75 - Kimi no na wa (2016) - Starring: Makoto Shinkai (dir.), Ryûnosuke Kamiki, Mone Kamishiraishi
76 - Coco (2017) - Starring: Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal
77 - Braveheart (1995) - Starring: Mel Gibson (dir.), Mel Gibson, Sophie Marceau
78 - Das Boot (1981) - Starring: Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer
79 - 3 Idiots (2009) - Starring: Rajkumar Hirani (dir.), Aamir Khan, Madhavan
80 - Star Wars: Episode VI - Return of the Jedi (1983) - Starring: Richard Marquand (dir.), Mark Hamill, Harrison Ford
81 - Taare Zameen Par (2007) - Starring: Aamir Khan (dir.), Darsheel Safary, Aamir Khan
82 - Toy Story (1995) - Starring: John Lasseter (dir.), Tom Hanks, Tim Allen
83 - Reservoir Dogs (1992) - Starring: Quentin Tarantino (dir.), Harvey Keitel, Tim Roth
84 - Amadeus (1984) - Starring: Milos Forman (dir.), F. Murray Abraham, Tom Hulce
85 - Inglourious Basterds (2009) - Starring: Quentin Tarantino (dir.), Brad Pitt, Diane Kruger
86 - Good Will Hunting (1997) - Starring: Gus Van Sant (dir.), Robin Williams, Matt Damon
87 - Dangal (2016) - Starring: Nitesh Tiwari (dir.), Aamir Khan, Sakshi Tanwar
88 - M - Eine Stadt sucht einen Mörder (1931) - Starring: Fritz Lang (dir.), Peter Lorre, Ellen Widmann
89 - Requiem for a Dream (2000) - Starring: Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto
90 - 2001: A Space Odyssey (1968) - Starring: Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood
91 - Vertigo (1958) - Starring: Alfred Hitchcock (dir.), James Stewart, Kim Novak
92 - Eternal Sunshine of the Spotless Mind (2004) - Starring: Michel Gondry (dir.), Jim Carrey, Kate Winslet
93 - Citizen Kane (1941) - Starring: Orson Welles (dir.), Orson Welles, Joseph Cotten
94 - Jagten (2012) - Starring: Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen
95 - Full Metal Jacket (1987) - Starring: Stanley Kubrick (dir.), Matthew Modine, R. Lee Ermey
96 - North by Northwest (1959) - Starring: Alfred Hitchcock (dir.), Cary Grant, Eva Marie Saint
97 - A Clockwork Orange (1971) - Starring: Stanley Kubrick (dir.), Malcolm McDowell, Patrick Magee
98 - Snatch (2000) - Starring: Guy Ritchie (dir.), Jason Statham, Brad Pitt
99 - The Kid (1921) - Starring: Charles Chaplin (dir.), Charles Chaplin, Edna Purviance
10 -  Amélie (2001) - Starring: Jean-Pierre Jeunet (dir.), Audrey Tautou, Mathieu Kassovitz
101 - Ladri di biciclette (1948) - Starring: Vittorio De Sica (dir.), Lamberto Maggiorani, Enzo Staiola
102 - Scarface (1983) - Starring: Brian De Palma (dir.), Al Pacino, Michelle Pfeiffer
103 - Singin' in the Rain (1952) - Starring: Stanley Donen (dir.), Gene Kelly, Donald O'Connor
104 - Taxi Driver (1976) - Starring: Martin Scorsese (dir.), Robert De Niro, Jodie Foster
105 - Lawrence of Arabia (1962) - Starring: David Lean (dir.), Peter O'Toole, Alec Guinness
106 - Toy Story 3 (2010) - Starring: Lee Unkrich (dir.), Tom Hanks, Tim Allen
107 - The Sting (1973) - Starring: George Roy Hill (dir.), Paul Newman, Robert Redford
108 - Metropolis (1927) - Starring: Fritz Lang (dir.), Brigitte Helm, Alfred Abel
109 - Per qualche dollaro in più (1965) - Starring: Sergio Leone (dir.), Clint Eastwood, Lee Van Cleef
110 - Ikiru (1952) - Starring: Akira Kurosawa (dir.), Takashi Shimura, Nobuo Kaneko
111 - Jodaeiye Nader az Simin (2011) - Starring: Asghar Farhadi (dir.), Payman Maadi, Leila Hatami
112 - Double Indemnity (1944) - Starring: Billy Wilder (dir.), Fred MacMurray, Barbara Stanwyck
113 - To Kill a Mockingbird (1962) - Starring: Robert Mulligan (dir.), Gregory Peck, John Megna
114 - Capharnaüm (2018) - Starring: Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw
115 - Indiana Jones and the Last Crusade (1989) - Starring: Steven Spielberg (dir.), Harrison Ford, Sean Connery
116 - The Apartment (1960) - Starring: Billy Wilder (dir.), Jack Lemmon, Shirley MacLaine
117 - Up (2009) - Starring: Pete Docter (dir.), Edward Asner, Jordan Nagai
118 - LA Confidential (1997) - Starring: Curtis Hanson (dir.), Kevin Spacey, Russell Crowe
119 - Monty Python and the Holy Grail (1975) - Starring: Terry Gilliam (dir.), Graham Chapman, John Cleese
120 - Incendies (2010) - Starring: Denis Villeneuve (dir.), Lubna Azabal, Mélissa Désormeaux-Poulin
121 - Heat (1995) - Starring: Michael Mann (dir.), Al Pacino, Robert De Niro
122 - Rashômon (1950) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Machiko Kyô
123 - Yôjinbô (1961) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Eijirô Tôno
124 - Die Hard (1988) - Starring: John McTiernan (dir.), Bruce Willis, Alan Rickman
125 - Batman Begins (2005) - Starring: Christopher Nolan (dir.), Christian Bale, Michael Caine
126 - Unforgiven (1992) - Starring: Clint Eastwood (dir.), Clint Eastwood, Gene Hackman
127 - Green Book (2018) - Starring: Peter Farrelly (dir.), Viggo Mortensen, Mahershala Ali
128 - Der Untergang (2004) - Starring: Oliver Hirschbiegel (dir.), Bruno Ganz, Alexandra Maria Lara
129 - Bacheha-Ye aseman (1997) - Starring: Majid Majidi (dir.), Mohammad Amir Naji, Amir Farrokh Hashemian
130 - Some Like It Hot (1959) - Starring: Billy Wilder (dir.), Marilyn Monroe, Tony Curtis
131 - Hauru no ugoku shiro (2004) - Starring: Hayao Miyazaki (dir.), Chieko Baishô, Takuya Kimura
132 - The Great Escape (1963) - Starring: John Sturges (dir.), Steve McQueen, James Garner
133 - Tonari no Totoro (1988) - Starring: Hayao Miyazaki (dir.), Hitoshi Takagi, Noriko Hidaka
134 - Ran (1985) - Starring: Akira Kurosawa (dir.), Tatsuya Nakadai, Akira Terao
135 - A Beautiful Mind (2001) - Starring: Ron Howard (dir.), Russell Crowe, Ed Harris
136 - All About Eve (1950) - Starring: Joseph L. Mankiewicz (dir.), Bette Davis, Anne Baxter
137 - Pan's Labyrinth (2006) - Starring: Guillermo del Toro (dir.), Ivana Baquero, Ariadna Gil
138 - Idi i smotri (1985) - Starring: Elem Klimov (dir.), Aleksey Kravchenko, Olga Mironova
139 - Casino (1995) - Starring: Martin Scorsese (dir.), Robert De Niro, Sharon Stone
140 - El secreto de sus ojos (2009) - Starring: Juan José Campanella (dir.), Ricardo Darín, Soledad Villamil
141 - Raging Bull (1980) - Starring: Martin Scorsese (dir.), Robert De Niro, Cathy Moriarty
142 - Lock, Stock and Two Smoking Barrels (1998) - Starring: Guy Ritchie (dir.), Jason Flemyng, Dexter Fletcher
143 - The Treasure of the Sierra Madre (1948) - Starring: John Huston (dir.), Humphrey Bogart, Walter Huston
144 - The Wolf of Wall Street (2013) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Jonah Hill
145 - Babam ve Oglum (2005) - Starring: Çagan Irmak (dir.), Çetin Tekindor, Fikret Kuskan
146 - Judgment at Nuremberg (1961) - Starring: Stanley Kramer (dir.), Spencer Tracy, Burt Lancaster
147 - Three Billboards Outside Ebbing, Missouri (2017) - Starring: Martin McDonagh (dir.), Frances McDormand, Woody Harrelson
148 - Drishyam (2013) - Starring: Jeethu Joseph (dir.), Asokan, Mohanlal
149 - Chinatown (1974) - Starring: Roman Polanski (dir.), Jack Nicholson, Faye Dunaway
150 - The Gold Rush (1925) - Starring: Charles Chaplin (dir.), Charles Chaplin, Mack Swain
151 - Dial M for Murder (1954) - Starring: Alfred Hitchcock (dir.), Ray Milland, Grace Kelly
152 - There Will Be Blood (2007) - Starring: Paul Thomas Anderson (dir.), Daniel Day-Lewis, Paul Dano
153 - V for Vendetta (2005) - Starring: James McTeigue (dir.), Hugo Weaving, Natalie Portman
154 - Inside Out (2015) - Starring: Pete Docter (dir.), Amy Poehler, Bill Hader
155 - Det sjunde inseglet (1957) - Starring: Ingmar Bergman (dir.), Max von Sydow, Gunnar Björnstrand
156 - Warrior (2011) - Starring: Gavin O'Connor (dir.), Tom Hardy, Nick Nolte
157 - No Country for Old Men (2007) - Starring: Ethan Coen (dir.), Tommy Lee Jones, Javier Bardem
158 - Room (2015) - Starring: Lenny Abrahamson (dir.), Brie Larson, Jacob Tremblay
159 - Trainspotting (1996) - Starring: Danny Boyle (dir.), Ewan McGregor, Ewen Bremner
160 - The Elephant Man (1980) - Starring: David Lynch (dir.), Anthony Hopkins, John Hurt
161 - The Sixth Sense (1999) - Starring: M. Night Shyamalan (dir.), Bruce Willis, Haley Joel Osment
162 - Shutter Island (2010) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Emily Mortimer
163 - The Thing (1982) - Starring: John Carpenter (dir.), Kurt Russell, Wilford Brimley
164 - Andhadhun (2018) - Starring: Sriram Raghavan (dir.), Ayushmann Khurrana, Tabu
165 - Gone with the Wind (1939) - Starring: Victor Fleming (dir.), Clark Gable, Vivien Leigh
166 - The Bridge on the River Kwai (1957) - Starring: David Lean (dir.), William Holden, Alec Guinness
167 - Blade Runner (1982) - Starring: Ridley Scott (dir.), Harrison Ford, Rutger Hauer
168 - The Third Man (1949) - Starring: Carol Reed (dir.), Orson Welles, Joseph Cotten
169 - On the Waterfront (1954) - Starring: Elia Kazan (dir.), Marlon Brando, Karl Malden
170 - Jurassic Park (1993) - Starring: Steven Spielberg (dir.), Sam Neill, Laura Dern
171 - Smultronstället (1957) - Starring: Ingmar Bergman (dir.), Victor Sjöström, Bibi Andersson
172 - Finding Nemo (2003) - Starring: Andrew Stanton (dir.), Albert Brooks, Ellen DeGeneres
173 - Eskiya (1996) - Starring: Yavuz Turgul (dir.), Sener Sen, Ugur Yücel
174 - Gran Torino (2008) - Starring: Clint Eastwood (dir.), Clint Eastwood, Bee Vang
175 - Fargo (1996) - Starring: Joel Coen (dir.), William H. Macy, Frances McDormand
176 - Kill Bill: Vol 1 (2003) - Starring: Quentin Tarantino (dir.), Uma Thurman, David Carradine
177 - The Deer Hunter (1978) - Starring: Michael Cimino (dir.), Robert De Niro, Christopher Walken
178 - Stalker (1979) - Starring: Andrei Tarkovsky (dir.), Alisa Freyndlikh, Aleksandr Kaydanovskiy
179 - The Truman Show (1998) - Starring: Peter Weir (dir.), Jim Carrey, Ed Harris
180 - Tôkyô monogatari (1953) - Starring: Yasujirô Ozu (dir.), Chishû Ryû, Chieko Higashiyama
181 - The Big Lebowski (1998) - Starring: Joel Coen (dir.), Jeff Bridges, John Goodman
182 - Relatos salvajes (2014) - Starring: Damián Szifron (dir.), Darío Grandinetti, María Marull
183 - Mary and Max (2009) - Starring: Adam Elliot (dir.), Toni Collette, Philip Seymour Hoffman
184 - In the Name of the Father (1993) - Starring: Jim Sheridan (dir.), Daniel Day-Lewis, Pete Postlethwaite
185 - Gone Girl (2014) - Starring: David Fincher (dir.), Ben Affleck, Rosamund Pike
186 - Hacksaw Ridge (2016) - Starring: Mel Gibson (dir.), Andrew Garfield, Sam Worthington
187 - The General (1926) - Starring: Clyde Bruckman (dir.), Buster Keaton, Marion Mack
188 - Sherlock Jr (1924) - Starring: Buster Keaton (dir.), Buster Keaton, Kathryn McGuire
189 - How to Train Your Dragon (2010) - Starring: Dean DeBlois (dir.), Jay Baruchel, Gerard Butler
190 - Mr Smith Goes to Washington (1939) - Starring: Frank Capra (dir.), James Stewart, Jean Arthur
191 - Salinui chueok (2003) - Starring: Joon-ho Bong (dir.), Kang-ho Song, Sang-kyung Kim
192 - The Grand Budapest Hotel (2014) - Starring: Wes Anderson (dir.), Ralph Fiennes, F. Murray Abraham
193 - Persona (1966) - Starring: Ingmar Bergman (dir.), Bibi Andersson, Liv Ullmann
194 - Before Sunrise (1995) - Starring: Richard Linklater (dir.), Ethan Hawke, Julie Delpy
195 - Catch Me If You Can (2002) - Starring: Steven Spielberg (dir.), Leonardo DiCaprio, Tom Hanks
196 - Into the Wild (2007) - Starring: Sean Penn (dir.), Emile Hirsch, Vince Vaughn
197 - Cool Hand Luke (1967) - Starring: Stuart Rosenberg (dir.), Paul Newman, George Kennedy
198 - Le salaire de la peur (1953) - Starring: Henri-Georges Clouzot (dir.), Yves Montand, Charles Vanel
199 - 12 Years a Slave (2013) - Starring: Steve McQueen (dir.), Chiwetel Ejiofor, Michael Kenneth Williams
200 - Prisoners (2013) - Starring: Denis Villeneuve (dir.), Hugh Jackman, Jake Gyllenhaal
201 - Network (1976) - Starring: Sidney Lumet (dir.), Faye Dunaway, William Holden
202 - Life of Brian (1979) - Starring: Terry Jones (dir.), Graham Chapman, John Cleese
203 - Stand by Me (1986) - Starring: Rob Reiner (dir.), Wil Wheaton, River Phoenix
204 - The Red Shoes (1948) - Starring: Michael Powell (dir.), Anton Walbrook, Marius Goring
205 - Mad Max: Fury Road (2015) - Starring: George Miller (dir.), Tom Hardy, Charlize Theron
206 - La passion de Jeanne d'Arc (1928) - Starring: Carl Theodor Dreyer (dir.), Maria Falconetti, Eugene Silvain
207 - Platoon (1986) - Starring: Oliver Stone (dir.), Charlie Sheen, Tom Berenger
208 - Rang De Basanti (2006) - Starring: Rakeysh Omprakash Mehra (dir.), Aamir Khan, Soha Ali Khan
209 - Million Dollar Baby (2004) - Starring: Clint Eastwood (dir.), Hilary Swank, Clint Eastwood
210 - Rush (2013) - Starring: Ron Howard (dir.), Daniel Brühl, Chris Hemsworth
211 - Hachi: A Dog's Tale (2009) - Starring: Lasse Hallström (dir.), Richard Gere, Joan Allen
212 - Andrei Rublev (1966) - Starring: Andrei Tarkovsky (dir.), Anatoliy Solonitsyn, Ivan Lapikov
213 - Barry Lyndon (1975) - Starring: Stanley Kubrick (dir.), Ryan O'Neal, Marisa Berenson
214 - Logan (2017) - Starring: James Mangold (dir.), Hugh Jackman, Patrick Stewart

In [1]:
from tkinter import *
from bs4 import BeautifulSoup
import requests
from PIL import Image, ImageTk

url = requests.get("https://pokemondb.net/pokedex/all")
soup = BeautifulSoup(url.content, 'html.parser')

#Data
pokemon_names = []
pokemon_hp = []
pokemon_attack = []
pokemon_defense = []
pokemon_speed = []
pokemon_types = []

names = soup.find_all('td', class_="cell-name")
for x in names:
    pokemon_names.append(x.get_text())

pokemon_name = [x.encode('utf-8') for x in pokemon_names]

types = soup.find_all('td', class_="cell-icon")
for x in types:
    pokemon_types.append(x.get_text())

pokemon_type = [x.encode('utf-8') for x in pokemon_types]    

other_data = []
for x in soup.find_all(attrs={'class': 'cell-num'}):
    other_data.append(x.get_text())

for i in range(1,len(other_data),7):
    pokemon_hp.append(other_data[i])

for i in range(2,len(other_data),7):
    pokemon_attack.append(other_data[i])

for i in range(3,len(other_data),7):
    pokemon_defense.append(other_data[i])

for i in range(6,len(other_data),7):
    pokemon_speed.append(other_data[i])

pokemon_hp = [int(i) for i in pokemon_hp]
pokemon_defense = [int(i) for i in pokemon_defense]
pokemon_attack = [int(i) for i in pokemon_attack]
pokemon_speed = [int(i) for i in pokemon_speed]

window = Tk()
window.configure(background="firebrick2")
window.geometry("525x700")
window.title("POKEDEX v.0.1")

#Labels
l1 = Label(window, text="ENTER A NUMBER: 0-925", width=25, bg="gray25", fg="ghost white", font=("Times", 14))#font size of word
l2 = Label(window, text="NAME", width=25, bg="gray25", fg="ghost white", font=("Times", 14))
l3 = Label(window, text="HP", width=25, bg="gray25", fg="ghost white", font=("Times", 14))
l4 = Label(window, text="ATTACK", width=25, bg="gray25", fg="ghost white", font=("Times", 14))
l5 = Label(window, text="DEFENSE", width=25, bg="gray25", fg="ghost white", font=("Times", 14))
l6 = Label(window, text="SPEED", width=25, bg="gray25", fg="ghost white", font=("Times", 14))
l7 = Label(window, text="TYPE", width=25, bg="gray25", fg="ghost white", font=("Times", 14))

l1.grid(row=1, column=0, pady=15)#pady to size of grid.
l2.grid(row=2, column=0, pady=5)
l3.grid(row=3, column=0, pady=5)
l4.grid(row=4, column=0, pady=5)
l5.grid(row=5, column=0, pady=5)
l6.grid(row=6, column=0, pady=5)
l7.grid(row=7, column=0, pady=5)

#Image
imagePath = "Pokeball.png"
i = Image.open(imagePath)
pokedex_image = ImageTk.PhotoImage(i)
i1 = Label(window, image=pokedex_image)
i1.grid(row=0, column=0, padx=10, pady=10)

#Text-Entries
e1 = Entry(window)
e2 = Text(window, width=25, height=1)
e3 = Text(window, width=25, height=1)
e4 = Text(window, width=25, height=1)
e5 = Text(window, width=25, height=1)
e6 = Text(window, width=25, height=1)
e7 = Text(window, width=25, height=1)

e1.grid(row=1, column=1, pady=5)
e2.grid(row=2, column=1, pady=5)
e3.grid(row=3, column=1, pady=5)
e4.grid(row=4, column=1, pady=5)
e5.grid(row=5, column=1, pady=5)
e6.grid(row=6, column=1, pady=5)
e7.grid(row=7, column=1, pady=5)

def insert_data():
    try:
        temp = e1.get()
        data = int(temp)
        e2.insert(END, pokemon_name[data])
        e3.insert(END, pokemon_hp[data])
        e4.insert(END, pokemon_attack[data])
        e5.insert(END, pokemon_defense[data])
        e6.insert(END, pokemon_speed[data])
        e7.insert(END, pokemon_type[data])
    except IndexError:
        print("Number should be between: 0-925")
    except ValueError:
        print("Input should be a number")
        
def clear():
    e2.delete('1.0', END)
    e3.delete('1.0', END)
    e4.delete('1.0', END)
    e5.delete('1.0', END)
    e6.delete('1.0', END)
    e7.delete('1.0', END)

#Buttons
b1 = Button(window, text="WHO'S THAT POKEMON?", command=insert_data, bg="forest green", fg="gray7", font=("Times", 16))

b2 = Button(window, text="QUIT", command=window.quit, bg="royal blue", fg="ghost white", font=("Times", 18))

b3 = Button(window, text="CLEAR", command=clear, bg="gold", fg="gray7", font=("Times", 16))

b1.grid(row=8, column=0, padx=5, pady=10)
b2.grid(row=8, column=1, padx=5, pady=10)
b3.grid(row=9, column=0, padx=5, pady=10)

#Start the Application
window.mainloop()

In [2]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
from tkinter import *
 
 
class ShowData():
    
 
    def __init__(self):
        self.root = Tk()
 
        self.titleVar = StringVar()
        self.textVar = StringVar()
        self.linksVar = StringVar()
 
        self.urlVar = StringVar()
 
        self.make_widgets()
 
        self.root.mainloop()
 
    def make_widgets(self):
        self.root.title("Web page scraper")
 
        self.startButton = Button(command = self.fill_widgets, text = "URL:").grid(padx = 5, row = 0, column = 0)
        self.urlField = Entry(textvariable = self.urlVar, width = 50).grid(padx = 5, pady = 5, row = 0, column = 1)
 
        self.titlePrmpt = Label(self.root, text = "Title:").grid(row = 1, column = 0)
        self.titleBox = Entry(self.root, textvariable = self.titleVar, width = 50).grid(row = 1, column = 1)
 
        self.textPrmpt = Label(self.root, text = "All text:").grid(row = 2, column = 0)
        self.textBox = Entry(self.root, textvariable = self.textVar, width = 100).grid(row = 2, column = 1)
 
        self.linksPrmpt = Label(self.root, text = "Hrefs:").grid(row = 3, column = 0)
        self.linksBox = Entry(self.root, textvariable = self.linksVar, width = 100).grid(row = 3, column = 1)
 
        self.allHtmlPrmpt = Label(self.root, text = "All HTML:").grid(row = 4, column = 0)
        self.allHtml = Text(self.root, width = 100)
        self.allHtml.grid(row = 4, column = 1)
 
    def fill_widgets(self):
        self.data = GetData(self.urlVar.get())
 
        self.titleVar.set(self.data.soupData["title"])
        self.textVar.set(self.data.soupData["text"])
        self.linksVar.set(self.data.soupData["hrefs"])
        self.allHtml.insert(END, self.data.soup.prettify())
 
 
class GetData():
    """ Get web-scraped data """
 
    def __init__(self, url):
        self.html = self.get_html(url)
        self.soup = BeautifulSoup(self.html)
        self.soupData = self.get_soup_data(self.soup)
 
    def get_html(self, url):
        raw = urlopen(url)
        return raw.read()
 
    def get_soup_data(self, soup):
        info = {"title": soup.title.string,
                "text": soup.get_text(),
                "links": soup.find_all("a"),
                "hrefs": []}
 
        for link in soup.find_all("a"):
            info["hrefs"].append(link.get("href"))
 
        return info
 
ShowData()

In [1]:
import urllib.request,urllib.error,urllib.parse
from bs4 import BeautifulSoup
html=urllib.request.urlopen("https://ums.lpu.in").read()
soap=BeautifulSoup(html,'html.parser')
tags=soap('a')
for tag in tags:
    print(tag.get('href',None))

https://ums.lpu.in/lpuums
https://ums.lpu.in/econnect
https://oas.lpu.in/
https://ums.lpu.in/induction
https://oms.lpu.in/
http://dashboards.lpu.in/
https://www.lpu.in/
http://www.lpude.in/
https://itunes.apple.com/in/app/lputouch/id509819753?mt=8
https://play.google.com/store/apps/details?id=ums.lovely.university

In [2]:
import urllib.request,urllib.error,urllib.parse
from bs4 import BeautifulSoup
html=urllib.request.urlopen("https://ums.lpu.in").read()
soap=BeautifulSoup(html,'html.parser')
tags=soap('img')
for tag in tags:
    print(tag.get('src',None))

images/lpu_logo.png
images/ums1.jpg
images/econnect1.jpg
images/oas.jpg
images/freshmen-induction.jpg
images/oms.jpg
images/lpu-dashboard.jpg
images/lpu.jpg
images/lpude.jpg
images/apple-store.png
images/google-play-store.png

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Vaibhav\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-5-28e33ccd9ec2>", line 42, in fill_widgets
    self.data = GetData(self.urlVar.get())
  File "<ipython-input-5-28e33ccd9ec2>", line 56, in __init__
    self.soupData = self.get_soup_data(self.soup)
  File "<ipython-input-5-28e33ccd9ec2>", line 69, in get_soup_data
    info["href"].append(link.get("src"))
KeyError: 'href'